### ISSUE TITLE
Always Runs Help

### ISSUE THREAD

**Issue by deltreey** [Ardesco/nasher4gh#2]
This always seems to run `--help` no matter what args I pass.

**Comment by Ardesco** [comment]
Can you link me to the job that is causing you problems so that i can look at your config

**Comment by deltreey** [comment]
honestly, this was 6 months ago.  I don't have the job handy.  I will try setting it up again.  It could've been user error.  I will close this an re-open if it's still an issue.

**Comment by deltreey** [comment]
Here's the action I was running.  I checked your docker image and the `CMD` is set to run `--help` but I also see that your code here __should__ override that.  It doesn't seem to on my runners.

```
      - name: Build module
        uses: Ardesco/nasher4gh@v1
        with:
          args: "['pack' '-y']"
```

**Comment by Ardesco** [comment]
Can you try:

      - name: Build module
        uses: Ardesco/nasher4gh@v1
        with:
          args: "['pack', '-y']"

Looks like you are missing a comma to separate the args.

**Comment by deltreey** [comment]
I tried it that way too.  No luck.  In fact, the reason the comma is not there is because of trying to make it work.

**Comment by Ardesco** [comment]
Don't suppose you have a public job you could link to so I can see the full workflow file and the run?

Also is -y supported or does it need to be --yes?  That might display help if it doesn't recognise -y,  you could try:

```
  - name: Build module
    uses: Ardesco/nasher4gh@v1
    with:
      args: "['pack', '--yes']"
```

**Comment by deltreey** [comment]
no change. Here's a screenshot

![Image](https://github.com/user-attachments/assets/4f0b1dc8-0067-4a54-87c7-724cd1eb108b)

**Comment by Ardesco** [comment]
I'm at a loss, it seems to be working fine for me.

![Image](https://github.com/user-attachments/assets/47e6f435-cdac-447e-be66-8e30f2812154)

Could you supply the entire workflow file, maybe you have something missing that I have in mine?

**Comment by deltreey** [comment]
Sure.  Of course, it fails before the last step here.

```yaml
name: Run CI Build

on: push

jobs:
  ci_build:
    runs-on: ubuntu-latest
    name: NWN:EE CI Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build module
        uses: Ardesco/nasher4gh@v1
        with:
          args: "['pack', '--yes']"
      - name: Upload Artifact
        run: |
          curl --user ${{secrets.CREDENTIALS}} --upload-file aayor.mod https://<my_gitea_server>/api/packages/eedevsln/generic/aayor-nwn/${{gitea.run_id}}/aayor.mod
          curl --user ${{secrets.CREDENTIALS}} -X DELETE https://<my_gitea_server>/api/packages/eedevsln/generic/aayor-nwn/latest/aayor.mod
          curl --user ${{secrets.CREDENTIALS}} --upload-file aayor.mod https://<my_gitea_server>/api/packages/eedevsln/generic/aayor-nwn/latest/aayor.mod          

```

**Comment by Ardesco** [comment]
I've been going over this and can't see why it doesn't work for you, all I can think is that the submodules may be causing some issues.

For the checkout step has it managed to successfully check out your code and all your submodules?

The docker image the action uses can be used to compile your code locally as well, you could try a local compile to see if that works (just to see if the image is capable of compiling your code, or there is some issue with it).

```
docker run --rm -it -v <PathToYourModuleCode>:/github/workspace ghcr.io/ardesco/nasher4gh-images:latest compile
```

**Comment by deltreey** [comment]
yes, check out runs fine.  Your docker command runs fine locally, but not sure if that says much about the runner.

![Image](https://github.com/user-attachments/assets/2d3ba553-8162-4e8c-949c-c998609138cf)

**Comment by Ardesco** [comment]
This is expecting to run the nasher command in the /github/workspace directory, if I'm reading this right it looks like you are checking out to /github/workspace/aayor-nwn (assumign the eedevsln directory has been mapped to /github/workspace).  

That could be the issue if it's running the command in one directory higher than expected.

Could you try tweaking your checkout action to:

```
 - uses: actions/checkout@v3
        with:
          submodules: true
          sparse-checkout: 'eedevsln/aayor-nwn'
          sparse-checkout-cone-mode: false
```
